### ISSUE TITLE
Hell yeah!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m2-evaluacion-intermedia-neired#1]
Really cool job @neired  !!!

Here you have some tips to improve the exercise:

### JavaScript

- [x] Define the logic to make the counter work
- [x] Use a constant to store the counter;

### Advanced

- [x] Move the feedback logic to a function an execute it on each click
- [x] Move you counter logic into a function and execute it on each click

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

**Comment by neired** [comment]
Dear Carlos aka Natalia,
Thank you so much for your review.
I have some questions though... When it comes to "define the logic", "move the logic"... I'm clueless about that, what does it mean? ><
I might ask you tomorrow in class, so maybe this message is more a reminder for myself ;)
Thanks in advance, see you tomorrow!

**Comment by oneeyedman** [comment]
Ok, pero el reseteo no funciona (creas una nueva constante local con el número aleatorio) y el contador sigue dependiendo de lo que haya escrito en el dom, cuando debería ser al revés.
